[package]
name = "telehash-rust"
version = "0.0.1"
authors = ["Jeremie Miller <jeremie@jabber.org>"]

[dependencies]
base32 = "0.3.0"

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide.git"
